build:
  test-gitium:
    image: presslabs/pl-test-containers:php-$$PHP_VERSION
    pull: true
    commands:
      - bash presslabs/bin/install-wp-tests.sh wordpress root wordpress localhost $$WP_VERSION true
      - composer update -q --no-suggest
      - dockerize --wait tcp://127.0.0.1:3306 -timeout 10s
      - make test
    environment:
      - WP_TESTS_DIR=/application/wordpress-tests-lib-$$WP_VERSION/
      - WP_CORE_DIR=/application/wordpress-$$WP_VERSION/

cache:
  mount:
    - vendor

compose:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=wordpress

matrix:
  WP_VERSION:
    - latest
  PHP_VERSION:
    - 7.0
    - 7.1
