
sudo: false

language: php

dist: trusty

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.0
  - 7.1
  - nightly

services:
  - mysql

env:
  global:
    - WP_TESTS_DIR=/tmp/wordpress-tests-lib
    - WP_CORE_DIR=/tmp/wordpress/
  matrix:
    - WP_VERSION=nightly WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=1
  allow_failures:
    - env: WP_VERSION=nightly WP_MULTISITE=0
    - env: WP_VERSION=latest WP_MULTISITE=1
    - php: nightly

addons:
  code_climate:
    repo_token: 819c356e2d022f98e4e2717dbd459c3801fef95241a2db7261596a0482dd6ca3

before_script:
  - mysql -e 'CREATE DATABASE wordpress_test;'
  - composer update
  - bash presslabs/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION true

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter